begin;
create extension if not exists pgtap with schema extensions;
select plan(36);
select has_table('private','ride_go_interests','conditional interests stay private');
select has_function('public','set_ride_go_interest',array['uuid','integer','boolean','uuid'],'interest command exists');
select has_function('public','get_ride_go_status',array['uuid'],'fresh own status exists');
insert into auth.users(id,email) values
('29000000-0000-4000-8000-000000000001','go-host@example.com'),
('29000000-0000-4000-8000-000000000002','go-rider@example.com'),
('29000000-0000-4000-8000-000000000003','go-peer@example.com');
update public.profiles set display_name='Go rider',handle='go_'||right(id::text,1),city='innsbruck',ability_level='chill',onboarding_completed=true
where id::text like '29000000-%';
insert into public.friendships(user_low,user_high,requested_by,status,responded_at) values
('29000000-0000-4000-8000-000000000001','29000000-0000-4000-8000-000000000002','29000000-0000-4000-8000-000000000001','accepted',now());
create temporary table go_state(key text primary key,value uuid);
grant all on go_state to authenticated;
set local role authenticated;
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000001';
insert into go_state values('ride',public.create_ride('stubai-glacier','chill',date_trunc('day',now())+interval '2 days 12 hours',4,'friends','Go test','Station',gen_random_uuid()));
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000002';
select is(public.get_ride_go_status((select value from go_state where key='ride')),null::jsonb,'no interest yields null');
insert into go_state values('key',gen_random_uuid());
insert into go_state values('interest',public.set_ride_go_interest((select value from go_state where key='ride'),3,true,(select value from go_state where key='key')));
select is(public.set_ride_go_interest((select value from go_state where key='ride'),3,true,(select value from go_state where key='key')),(select value from go_state where key='interest'),'retry is idempotent');
select throws_ok(format('select public.set_ride_go_interest(%L,2,true,%L)',(select value from go_state where key='ride'),(select value from go_state where key='key')),'22023','idempotency key payload mismatch','mismatched retry rejected');
select is(public.get_ride_go_status((select value from go_state where key='ride'))->>'status','interested','interest never joins');
select is(public.get_ride_go_status((select value from go_state where key='ride'))->>'confirmedGroup','1','only host initially confirmed');
select throws_ok(format('select public.request_ride(%L,gen_random_uuid())',(select value from go_state where key='ride')),'23514','go conditions not ready','request requires ready conditions');
reset role;
insert into public.ride_members(ride_id,user_id,role) select value,'29000000-0000-4000-8000-000000000003','participant' from go_state where key='ride';
set local role authenticated;
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000001';
insert into go_state values('carpool',public.create_carpool('stubai-glacier','innsbruck','driver',date_trunc('day',now())+interval '2 days 9 hours',2,'friends','Go seat','Station',gen_random_uuid()));
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000002';
select is(public.get_ride_go_status((select value from go_state where key='ride'))->>'groupReady','true','confirmed group fulfills group condition');
select is(public.get_ride_go_status((select value from go_state where key='ride'))->>'carpoolReady','false','offer alone never reserves a seat');
select throws_ok(format('select public.set_ride_go_interest(%L,5,false,gen_random_uuid())',(select value from go_state where key='ride')),'23514','invalid go conditions','minimum cannot exceed ride capacity');
insert into go_state values('seatrequest',public.request_carpool((select value from go_state where key='carpool'),gen_random_uuid()));
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000001';
select public.respond_carpool_request((select value from go_state where key='seatrequest'),true,gen_random_uuid());
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000002';
select is(public.get_ride_go_status((select value from go_state where key='ride'))->>'status','ready','accepted seat fulfills transport condition');
reset role;
update public.carpools set departs_at=departs_at+interval '1 day' where id=(select value from go_state where key='carpool');
set local role authenticated;
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000002';
select is(public.get_ride_go_status((select value from go_state where key='ride'))->>'carpoolReady','false','seat on different day excluded');
reset role;
update public.carpools set departs_at=date_trunc('day',now())+interval '2 days 14 hours' where id=(select value from go_state where key='carpool');
set local role authenticated;
select is(public.get_ride_go_status((select value from go_state where key='ride'))->>'carpoolReady','false','departure after ride excluded');
reset role;
update public.carpools set departs_at=date_trunc('day',now())+interval '2 days 9 hours',resort_id='axamer-lizum' where id=(select value from go_state where key='carpool');
set local role authenticated;
select is(public.get_ride_go_status((select value from go_state where key='ride'))->>'carpoolReady','false','different destination excluded');
reset role;
update public.carpools set resort_id='stubai-glacier',status='cancelled' where id=(select value from go_state where key='carpool');
set local role authenticated;
select is(public.get_ride_go_status((select value from go_state where key='ride'))->>'carpoolReady','false','cancelled offer excluded');
reset role;
update public.carpools set status='scheduled' where id=(select value from go_state where key='carpool');
update public.rides set starts_at=statement_timestamp()+interval '1 second' where id=(select value from go_state where key='ride');
update public.carpools set status='active',departs_at=statement_timestamp()-interval '1 microsecond' where id=(select value from go_state where key='carpool');
set local role authenticated;
select is(public.get_ride_go_status((select value from go_state where key='ride'))->>'carpoolReady','true','confirmed transport remains valid after departure during active journey');
reset role;
update public.rides set starts_at=date_trunc('day',now())+interval '2 days 12 hours' where id=(select value from go_state where key='ride');
update public.carpools set status='scheduled',departs_at=date_trunc('day',now())+interval '2 days 9 hours' where id=(select value from go_state where key='carpool');
set local role authenticated;
insert into go_state values('request',public.request_ride((select value from go_state where key='ride'),gen_random_uuid()));
select is(public.get_ride_go_status((select value from go_state where key='ride'))->>'status','requested','explicit request remains pending');
select public.withdraw_ride_go_interest((select value from go_state where key='ride'),gen_random_uuid());
reset role;
select is((select status from public.ride_join_requests where id=(select value from go_state where key='request')),'cancelled','withdrawing wish also cancels pending explicit request');
set local role authenticated;
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000002';
select public.set_ride_go_interest((select value from go_state where key='ride'),3,true,gen_random_uuid());
select public.request_ride((select value from go_state where key='ride'),gen_random_uuid());
select is(public.get_ride_go_status((select value from go_state where key='ride'))->>'status','requested','new explicit request after reset is pending');
select public.leave_carpool((select value from go_state where key='carpool'),gen_random_uuid());
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000001';
select throws_ok(format('select public.respond_ride_request(%L,true,gen_random_uuid())',(select value from go_state where key='request')),'23514','go conditions not ready','seat loss blocks later host acceptance');
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000002';
select public.set_ride_go_interest((select value from go_state where key='ride'),2,false,gen_random_uuid());
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000001';
select public.respond_ride_request((select value from go_state where key='request'),true,gen_random_uuid());
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000002';
select is(public.get_ride_go_status((select value from go_state where key='ride'))->>'status','confirmed','host acceptance explicitly confirms');
reset role;
delete from public.ride_members where user_id='29000000-0000-4000-8000-000000000003';
update private.ride_go_interests set minimum_group=3 where user_id='29000000-0000-4000-8000-000000000002';
set local role authenticated;
select is(public.get_ride_go_status((select value from go_state where key='ride'))->>'ready','false','changed group reevaluates confirmed conditions');
select is(public.get_ride_go_status((select value from go_state where key='ride'))->>'status','confirmed','changed condition does not silently remove membership');
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000001';
insert into go_state values('pairride',public.create_ride('stubai-glacier','chill',date_trunc('day',now())+interval '2 days 12 hours',2,'friends','Pair test','Station',gen_random_uuid()));
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000002';
select public.set_ride_go_interest((select value from go_state where key='pairride'),2,true,gen_random_uuid());
insert into go_state values('ridersearch',public.create_carpool('stubai-glacier','innsbruck','rider',date_trunc('day',now())+interval '2 days 9 hours',1,'friends','Need lift','Station',gen_random_uuid()));
select is(public.get_ride_go_status((select value from go_state where key='pairride'))->>'carpoolReady','false','own rider search alone never confirms transport');
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000001';
insert into go_state values('driverrequest',public.request_carpool((select value from go_state where key='ridersearch'),gen_random_uuid()));
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000002';
select public.respond_carpool_request((select value from go_state where key='driverrequest'),true,gen_random_uuid());
select is(public.get_ride_go_status((select value from go_state where key='pairride'))->>'ready','true','accepted driver for rider search fulfills conditions for capacity2');
insert into go_state values('pairrequest',public.request_ride((select value from go_state where key='pairride'),gen_random_uuid()));
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000001';
select public.respond_ride_request((select value from go_state where key='pairrequest'),true,gen_random_uuid());
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000002';
select is(public.get_ride_go_status((select value from go_state where key='pairride'))->>'status','confirmed','two person ride can explicitly confirm');
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000001';
select public.leave_carpool((select value from go_state where key='ridersearch'),gen_random_uuid());
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000002';
select is(public.get_ride_go_status((select value from go_state where key='pairride'))->>'ready','false','driver leaving rider search reevaluates confirmed wish');
select public.withdraw_ride_go_interest((select value from go_state where key='ride'),gen_random_uuid());
select is(public.get_ride_go_status((select value from go_state where key='ride'))->>'status','withdrawn','interest withdrawal persists');
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000003';
select is(public.get_ride_go_status((select value from go_state where key='ride')),null::jsonb,'peer cannot read another interest');
reset role;
select ok(not has_table_privilege('authenticated','private.ride_go_interests','SELECT'),'raw interests inaccessible');
select ok((private.build_account_export('29000000-0000-4000-8000-000000000002')->'ride_go_interests') is not null,'interests included in account export');
update public.rides set starts_at=now()-interval '2 days' where id=(select value from go_state where key='ride');
select * from private.cleanup_expired_coordination_data(statement_timestamp());
select is((select count(*) from private.ride_go_interests where ride_id=(select value from go_state where key='ride')),0::bigint,'expired wishes removed after24hours');
insert into private.ride_go_interests(ride_id,user_id,minimum_group,needs_carpool)
select value,'29000000-0000-4000-8000-000000000002',2,false from go_state where key='ride';
set local role authenticated;
set local request.jwt.claim.sub='29000000-0000-4000-8000-000000000002';
select is(public.get_ride_go_status((select value from go_state where key='ride'))->>'status','expired','past departure expires interest');
reset role;
delete from auth.users where id='29000000-0000-4000-8000-000000000002';
select is((select count(*) from private.ride_go_interests where user_id='29000000-0000-4000-8000-000000000002'),0::bigint,'account deletion cascades');
select * from finish();
rollback;
