begin;
create extension if not exists pgtap with schema extensions;
select plan(31);
select has_table('private','pistl_website_waitlist','waitlist data private');
select has_function('public','pistl_request_waitlist',array['text','boolean','text','text'],'website request contract exists');
select has_function('public','pistl_confirm_waitlist',array['text'],'website confirmation contract exists');
select has_function('public','pistl_release_waitlist_token',array['text'],'failed mail release exists');
select ok(not has_function_privilege('authenticated','public.pistl_request_waitlist(text,boolean,text,text)','EXECUTE'),'signed in app clients cannot submit service RPC');
select ok(not has_function_privilege('anon','public.pistl_confirm_waitlist(text)','EXECUTE'),'anonymous client cannot confirm directly');
select ok(not has_table_privilege('service_role','private.pistl_website_waitlist','SELECT'),'service cannot read raw waitlist table');
set local role service_role;
select is(public.pistl_request_waitlist('waitlist-case@example.com',true,repeat('a',64),repeat('1',64)),'send','first request sends confirmation');
reset role;
select ok((select confirmed_at is null and not early_access and pending_early_access from private.pistl_website_waitlist where email='waitlist-case@example.com'),'interest never confirms or grants early access');
set local role service_role;
select is(public.pistl_request_waitlist('waitlist-case@example.com',false,repeat('a',64),repeat('2',64)),'wait','cooldown protects existing confirmation');
reset role;
select ok((select token_hash=repeat('1',64) and pending_early_access from private.pistl_website_waitlist where email='waitlist-case@example.com'),'cooldown never changes token-bound preference');
set local role service_role;
select is(public.pistl_confirm_waitlist(repeat('1',64)),'confirmed','explicit confirmation commits consent');
select is(public.pistl_confirm_waitlist(repeat('1',64)),'confirmed','confirmation retry is idempotent');
select is(public.pistl_request_waitlist('waitlist-case@example.com',false,repeat('a',64),repeat('3',64)),'confirmed','confirmed email never gets another mail');
reset role;
select ok((select early_access and early_access_consent_at is not null and confirmed_at=consent_at from private.pistl_website_waitlist where email='waitlist-case@example.com'),'unverified submission cannot change confirmed consent');
set local role service_role;
select is(public.pistl_request_waitlist('waitlist-release@example.com',false,repeat('b',64),repeat('4',64)),'send','second address sends');
select public.pistl_release_waitlist_token(repeat('4',64));
select is(public.pistl_confirm_waitlist(repeat('4',64)),'invalid','failed delivery token revoked');
select is(public.pistl_request_waitlist('waitlist-release@example.com',false,repeat('b',64),repeat('5',64)),'send','failed delivery can retry immediately');
select public.pistl_release_waitlist_token(repeat('4',64));
select is(public.pistl_confirm_waitlist(repeat('5',64)),'confirmed','late release never revokes replacement token');
select public.pistl_release_waitlist_token(repeat('5',64));
select is(public.pistl_confirm_waitlist(repeat('5',64)),'confirmed','release never changes confirmed consent');
select is(public.pistl_confirm_waitlist(repeat('6',64)),'invalid','unknown hash cannot confirm');
select is(public.pistl_confirm_waitlist('plaintext-token'),'invalid','raw tokens never match');
select throws_ok($$select public.pistl_request_waitlist('BAD@example.com',false,repeat('d',64),repeat('7',64))$$,'22023','invalid waitlist input','unnormalized email rejected');
select public.pistl_request_waitlist('waitlist-rate@example.com',false,repeat('c',64),repeat('8',64));
select public.pistl_request_waitlist('waitlist-rate@example.com',false,repeat('c',64),repeat('8',64));
select public.pistl_request_waitlist('waitlist-rate@example.com',false,repeat('c',64),repeat('8',64));
select public.pistl_request_waitlist('waitlist-rate@example.com',false,repeat('c',64),repeat('8',64));
select public.pistl_request_waitlist('waitlist-rate@example.com',false,repeat('c',64),repeat('8',64));
select is(public.pistl_request_waitlist('waitlist-rate@example.com',false,repeat('c',64),repeat('8',64)),'rate_limited','sixth attempt limited even when cooldown already active');
reset role;
update private.pistl_website_waitlist set token_expires_at=statement_timestamp()-interval '1 second' where email='waitlist-rate@example.com';
set local role service_role;
select is(public.pistl_confirm_waitlist(repeat('8',64)),'invalid','expired token rejected');
reset role;
update private.pistl_website_rate_limits set window_start=statement_timestamp()-interval '2 hours' where rate_key=repeat('c',64);
update private.pistl_website_waitlist set last_sent_at=statement_timestamp()-interval '6 minutes' where email='waitlist-rate@example.com';
set local role service_role;
select is(public.pistl_request_waitlist('waitlist-rate@example.com',true,repeat('c',64),repeat('9',64)),'send','new hour resets rate and elapsed cooldown permits resend');
select is(public.pistl_confirm_waitlist(repeat('8',64)),'invalid','reissued confirmation revokes old token');
reset role;
select ok((select token_expires_at>statement_timestamp()+interval '6 days' and pending_early_access from private.pistl_website_waitlist where email='waitlist-rate@example.com'),'new token binds new preference and seven-day validity');
update private.pistl_website_waitlist set requested_at=statement_timestamp()-interval '8 days',token_hash=null,token_expires_at=null,last_sent_at=null where email='waitlist-rate@example.com';
update private.pistl_website_rate_limits set window_start=statement_timestamp()-interval '25 hours';
update private.pistl_website_waitlist set token_expires_at=statement_timestamp()-interval '1 second' where email='waitlist-case@example.com';
select private.cleanup_website_waitlist(statement_timestamp());
select ok((select token_hash is null and token_expires_at is null and confirmed_at is not null and early_access from private.pistl_website_waitlist where email='waitlist-case@example.com'),'cleanup removes expired confirmed tokens without removing confirmed consent');
select is((select count(*) from private.pistl_website_waitlist where email='waitlist-rate@example.com'),0::bigint,'expired released requests are cleaned without token expiry');
select is((select count(*) from private.pistl_website_rate_limits),0::bigint,'rate digests removed after24hours');
select * from finish();
rollback;
