import { User, RidePost, CarpoolPost, ResortStatus, Badge, LeaderboardEntry, Crew, Conversation } from "./types";

export const BADGES: Badge[] = [
  { id: "first_tracks", name: "First Tracks", description: "Rode before 8am on a powder day", rarity: "rare", icon: "sunrise" },
  { id: "storm_chaser", name: "Storm Chaser", description: "Posted a ride during a snowstorm", rarity: "epic", icon: "snowflake" },
  { id: "local_legend", name: "Local Legend", description: "10+ rides at the same resort", rarity: "rare", icon: "mountain" },
  { id: "crew_builder", name: "Crew Builder", description: "Invited 5+ friends to Snowmate", rarity: "common", icon: "users" },
  { id: "powder_hound", name: "Powder Hound", description: "20+ powder days logged", rarity: "epic", icon: "wind" },
  { id: "season_warrior", name: "Season Warrior", description: "30+ days in one season", rarity: "epic", icon: "trophy" },
  { id: "night_rider", name: "Night Rider", description: "5+ après sessions with crew", rarity: "common", icon: "moon" },
  { id: "dawn_patrol", name: "Dawn Patrol", description: "10+ rides before 9am", rarity: "rare", icon: "alarm" },
  { id: "carpool_king", name: "Carpool King", description: "Offered 10+ rides to resorts", rarity: "common", icon: "car" },
  { id: "multi_pass", name: "Multi-Pass", description: "Rode 5+ different resorts", rarity: "common", icon: "map" },
];

export const MOCK_USERS: User[] = [
  {
    id: "me",
    name: "Felix Gruber",
    handle: "felix.gruber",
    avatar: "FG",
    city: "innsbruck",
    level: 4,
    levelTitle: "Local",
    xp: 2340,
    xpToNext: 3000,
    isMinor: false,
    accountType: "standard",
    daysThisSeason: 23,
    resortsVisited: 7,
    friendsInvited: 4,
    streakWeeks: 6,
    badges: ["first_tracks", "crew_builder", "night_rider", "carpool_king", "multi_pass"],
    friendIds: ["u1", "u2", "u3", "u4", "u5"],
    instagram: "felix.gruber",
    bio: "Nordkette local. Off-piste + park. Stubai on powder days.",
    favoriteResort: "Nordkette",
    isPremium: false,
  },
  {
    id: "u1",
    name: "Sophie Wagner",
    handle: "sophie.w",
    avatar: "SW",
    city: "innsbruck",
    level: 6,
    levelTitle: "Regular",
    xp: 5100,
    xpToNext: 6000,
    isMinor: false,
    accountType: "standard",
    daysThisSeason: 41,
    resortsVisited: 11,
    friendsInvited: 9,
    streakWeeks: 12,
    badges: ["first_tracks", "storm_chaser", "local_legend", "crew_builder", "powder_hound", "season_warrior", "dawn_patrol", "multi_pass"],
    friendIds: ["me", "u2", "u3"],
    instagram: "sophiewagner.ski",
    snapchat: "sophiewsk",
    bio: "Powder chaser. Stubai Glacier season pass holder. Early starts only.",
    favoriteResort: "Stubai Glacier",
    isPremium: true,
  },
  {
    id: "u2",
    name: "Max Huber",
    handle: "maxhuber",
    avatar: "MH",
    city: "innsbruck",
    level: 3,
    levelTitle: "Rookie",
    xp: 1200,
    xpToNext: 2000,
    isMinor: false,
    accountType: "standard",
    daysThisSeason: 11,
    resortsVisited: 4,
    friendsInvited: 2,
    streakWeeks: 3,
    badges: ["crew_builder", "night_rider"],
    friendIds: ["me", "u1"],
    snapchat: "maxhuber99",
    bio: "Park rider. Nordkette jibber. Always down for après.",
    favoriteResort: "Nordkette",
    isPremium: false,
  },
  {
    id: "u3",
    name: "Julia Mayer",
    handle: "juli.mayer",
    avatar: "JM",
    city: "innsbruck",
    level: 5,
    levelTitle: "Regular",
    xp: 3800,
    xpToNext: 4500,
    isMinor: false,
    accountType: "standard",
    daysThisSeason: 31,
    resortsVisited: 9,
    friendsInvited: 7,
    streakWeeks: 9,
    badges: ["first_tracks", "local_legend", "crew_builder", "season_warrior", "carpool_king"],
    friendIds: ["me", "u1", "u4"],
    instagram: "juli.mayer",
    bio: "Carpool queen of Innsbruck. Any resort, any weather.",
    favoriteResort: "Axamer Lizum",
    isPremium: true,
  },
  {
    id: "u4",
    name: "Tobias Kern",
    handle: "tobi.k",
    avatar: "TK",
    city: "innsbruck",
    level: 2,
    levelTitle: "Rookie",
    xp: 580,
    xpToNext: 1000,
    isMinor: true,
    accountType: "standard",
    daysThisSeason: 6,
    resortsVisited: 2,
    friendsInvited: 1,
    streakWeeks: 2,
    badges: ["night_rider"],
    friendIds: ["me", "u3"],
    snapchat: "tobias_k02",
    bio: "Just getting started. Chill runs only for now.",
    favoriteResort: "Axamer Lizum",
    isPremium: false,
  },
  {
    id: "u5",
    name: "Anna Hofer",
    handle: "anna.hofer",
    avatar: "AH",
    city: "salzburg",
    level: 7,
    levelTitle: "Legend",
    xp: 7200,
    xpToNext: 9000,
    isMinor: false,
    accountType: "verified",
    daysThisSeason: 58,
    resortsVisited: 13,
    friendsInvited: 15,
    streakWeeks: 18,
    badges: ["first_tracks", "storm_chaser", "local_legend", "crew_builder", "powder_hound", "season_warrior", "night_rider", "dawn_patrol", "carpool_king", "multi_pass"],
    friendIds: ["me", "u6"],
    instagram: "anna.hofer.ski",
    snapchat: "annahofer",
    bio: "Ski guide. Saalbach local. Storm days are best days.",
    favoriteResort: "Saalbach-Hinterglemm",
    isPremium: true,
  },
  {
    id: "u6",
    name: "Florian Mayr",
    handle: "flo.mayr",
    avatar: "FM",
    city: "innsbruck",
    level: 4,
    levelTitle: "Local",
    xp: 2900,
    xpToNext: 3000,
    isMinor: false,
    accountType: "standard",
    daysThisSeason: 19,
    resortsVisited: 6,
    friendsInvited: 3,
    streakWeeks: 5,
    badges: ["crew_builder", "carpool_king", "multi_pass"],
    friendIds: ["u5", "u7"],
    instagram: "flomayr",
    bio: "Van driver. Always has space for one more.",
    favoriteResort: "Schlick 2000",
    isPremium: false,
  },
  {
    id: "u7",
    name: "Clara Schmid",
    handle: "clara.s",
    avatar: "CS",
    city: "innsbruck",
    level: 3,
    levelTitle: "Rookie",
    xp: 1650,
    xpToNext: 2000,
    isMinor: false,
    accountType: "standard",
    daysThisSeason: 14,
    resortsVisited: 5,
    friendsInvited: 2,
    streakWeeks: 4,
    badges: ["night_rider", "crew_builder"],
    friendIds: ["u6", "u8"],
    snapchat: "clara.schmid",
    bio: "Erasmus student. Learning to ski this season. Patient crew only!",
    favoriteResort: "Mutterer Alm",
    isPremium: false,
  },
  {
    id: "u8",
    name: "David Winkler",
    handle: "dav.winkler",
    avatar: "DW",
    city: "salzburg",
    level: 5,
    levelTitle: "Regular",
    xp: 4100,
    xpToNext: 4500,
    isMinor: false,
    accountType: "standard",
    daysThisSeason: 28,
    resortsVisited: 8,
    friendsInvited: 6,
    streakWeeks: 7,
    badges: ["first_tracks", "local_legend", "crew_builder", "carpool_king"],
    friendIds: ["u7"],
    instagram: "david.winkler.skis",
    bio: "Park & freeride. Kitzsteinhorn obsessed.",
    favoriteResort: "Kitzsteinhorn",
    isPremium: false,
  },
];

export const RIDE_POSTS: RidePost[] = [
  {
    id: "r1",
    authorId: "u1",
    resort: "Stubai Glacier",
    city: "innsbruck",
    abilityLevel: "off-piste",
    date: "Today",
    meetTime: "08:30",
    meetPoint: "Talstation Wildspitzbahn",
    totalSpots: 4,
    takenSpots: 2,
    joinedUserIds: ["u2", "u3"],
    caption: "Powder day! Glacier is untouched. Who's in? Let's head out early — carpool from Innsbruck HBF possible.",
    postedAt: "23 min ago",
  },
  {
    id: "r2",
    authorId: "u3",
    resort: "Nordkette",
    city: "innsbruck",
    abilityLevel: "park",
    date: "Today",
    meetTime: "10:00",
    meetPoint: "Congress Station",
    totalSpots: 6,
    takenSpots: 3,
    joinedUserIds: ["u6", "u7", "u4"],
    caption: "Park session at Nordkette, doing rails. Intermediate+ only. Bring a helmet.",
    postedAt: "1 hr ago",
  },
  {
    id: "r3",
    authorId: "u6",
    resort: "Axamer Lizum",
    city: "innsbruck",
    abilityLevel: "chill",
    date: "Today",
    meetTime: "11:00",
    meetPoint: "Parkplatz Axamer Lizum",
    totalSpots: 8,
    takenSpots: 5,
    joinedUserIds: ["u2", "u4", "u7", "u8", "u5"],
    caption: "Chill day, blue runs only. Bring your beginners along. I've got space in the van.",
    postedAt: "2 hr ago",
  },
  {
    id: "r4",
    authorId: "u2",
    resort: "Schlick 2000",
    city: "innsbruck",
    abilityLevel: "chill",
    date: "Today",
    meetTime: "09:45",
    meetPoint: "Fulpmes Bahnhof",
    totalSpots: 5,
    takenSpots: 4,
    joinedUserIds: ["u3", "u4", "u6"],
    caption: "Last spot open! Come along.",
    postedAt: "3 hr ago",
  },
  {
    id: "r5",
    authorId: "u5",
    resort: "Saalbach-Hinterglemm",
    city: "salzburg",
    abilityLevel: "off-piste",
    date: "Today",
    meetTime: "07:45",
    meetPoint: "Saalbach Dorfplatz",
    totalSpots: 3,
    takenSpots: 1,
    joinedUserIds: ["u8"],
    caption: "Early start, deep snow on Kohlmais. I know the area blind — happy to guide.",
    postedAt: "45 min ago",
  },
  {
    id: "r6",
    authorId: "u8",
    resort: "Flachau",
    city: "salzburg",
    abilityLevel: "park",
    date: "Today",
    meetTime: "12:00",
    meetPoint: "Flachau Ortszentrum",
    totalSpots: 4,
    takenSpots: 2,
    joinedUserIds: ["u5", "u6"],
    caption: "Afternoon park session at the Nachtslalom area. Sick kicker setup today.",
    postedAt: "1 hr ago",
  },
];

export const CARPOOL_POSTS: CarpoolPost[] = [
  {
    id: "c1",
    authorId: "u1",
    role: "driver",
    resort: "Stubai Glacier",
    city: "innsbruck",
    departurePoint: "Innsbruck HBF",
    departureTime: "07:30",
    totalSeats: 3,
    availableSeats: 2,
    riders: ["u2"],
    note: "Got room for two more, luggage no problem.",
    postedAt: "1 hr ago",
  },
  {
    id: "c2",
    authorId: "u4",
    role: "rider",
    resort: "Axamer Lizum",
    city: "innsbruck",
    departurePoint: "Anywhere, Innsbruck city center",
    departureTime: "09:00",
    totalSeats: 1,
    availableSeats: 1,
    riders: [],
    note: "Looking for a ride, I'll chip in for gas.",
    postedAt: "2 hr ago",
  },
  {
    id: "c3",
    authorId: "u3",
    role: "driver",
    resort: "Nordkette",
    city: "innsbruck",
    departurePoint: "Wilten, Innsbruck",
    departureTime: "09:30",
    totalSeats: 4,
    availableSeats: 3,
    riders: ["u6"],
    note: "Leaving after breakfast, easy 5 min drive.",
    postedAt: "3 hr ago",
  },
  {
    id: "c4",
    authorId: "u5",
    role: "driver",
    resort: "Saalbach-Hinterglemm",
    city: "salzburg",
    departurePoint: "Salzburg HBF",
    departureTime: "07:00",
    totalSeats: 4,
    availableSeats: 2,
    riders: ["u8", "u7"],
    note: "Early start, be on time please. Heading back around 16:00.",
    postedAt: "30 min ago",
  },
  {
    id: "c5",
    authorId: "u7",
    role: "rider",
    resort: "Kitzsteinhorn",
    city: "salzburg",
    departurePoint: "Anif or Hallein",
    departureTime: "08:00",
    totalSeats: 1,
    availableSeats: 1,
    riders: [],
    note: "Looking for a ride to the glacier, I'm punctual.",
    postedAt: "4 hr ago",
  },
];

export const RESORT_STATUS: ResortStatus[] = [
  { name: "Stubai Glacier", city: "innsbruck", ridersNow: 28, chillRiders: 8, parkRiders: 4, offPisteRiders: 16, conditions: "fresh", liftsOpen: 12, totalLifts: 14, snowDepth: 210, altitudeMax: 3210, altitudeMin: 1750, mountainShape: 0 },
  { name: "Nordkette", city: "innsbruck", ridersNow: 19, chillRiders: 5, parkRiders: 9, offPisteRiders: 5, conditions: "groomed", liftsOpen: 4, totalLifts: 5, snowDepth: 85, altitudeMax: 2334, altitudeMin: 574, mountainShape: 1 },
  { name: "Axamer Lizum", city: "innsbruck", ridersNow: 34, chillRiders: 18, parkRiders: 6, offPisteRiders: 10, conditions: "groomed", liftsOpen: 8, totalLifts: 9, snowDepth: 120, altitudeMax: 2340, altitudeMin: 1560, mountainShape: 2 },
  { name: "Schlick 2000", city: "innsbruck", ridersNow: 22, chillRiders: 14, parkRiders: 3, offPisteRiders: 5, conditions: "fresh", liftsOpen: 6, totalLifts: 7, snowDepth: 95, altitudeMax: 2136, altitudeMin: 980, mountainShape: 3 },
  { name: "Kühtai", city: "innsbruck", ridersNow: 15, chillRiders: 7, parkRiders: 5, offPisteRiders: 3, conditions: "groomed", liftsOpen: 7, totalLifts: 9, snowDepth: 145, altitudeMax: 2520, altitudeMin: 2020, mountainShape: 4 },
  { name: "Glungezer", city: "innsbruck", ridersNow: 8, chillRiders: 4, parkRiders: 0, offPisteRiders: 4, conditions: "fresh", liftsOpen: 4, totalLifts: 5, snowDepth: 110, altitudeMax: 2677, altitudeMin: 1900, mountainShape: 0 },
  { name: "Patscherkofel", city: "innsbruck", ridersNow: 11, chillRiders: 6, parkRiders: 2, offPisteRiders: 3, conditions: "groomed", liftsOpen: 3, totalLifts: 4, snowDepth: 80, altitudeMax: 2246, altitudeMin: 1000, mountainShape: 1 },
  { name: "Bergeralm", city: "innsbruck", ridersNow: 6, chillRiders: 4, parkRiders: 1, offPisteRiders: 1, conditions: "icy", liftsOpen: 3, totalLifts: 4, snowDepth: 60, altitudeMax: 2000, altitudeMin: 950, mountainShape: 2 },
  { name: "Rangger Köpfl", city: "innsbruck", ridersNow: 9, chillRiders: 7, parkRiders: 0, offPisteRiders: 2, conditions: "groomed", liftsOpen: 3, totalLifts: 3, snowDepth: 75, altitudeMax: 1940, altitudeMin: 870, mountainShape: 3 },
  { name: "Hochoetz", city: "innsbruck", ridersNow: 17, chillRiders: 9, parkRiders: 4, offPisteRiders: 4, conditions: "groomed", liftsOpen: 10, totalLifts: 11, snowDepth: 130, altitudeMax: 2840, altitudeMin: 820, mountainShape: 4 },
  { name: "Mutterer Alm", city: "innsbruck", ridersNow: 5, chillRiders: 3, parkRiders: 0, offPisteRiders: 2, conditions: "groomed", liftsOpen: 3, totalLifts: 4, snowDepth: 70, altitudeMax: 1900, altitudeMin: 900, mountainShape: 0 },
  { name: "Serlesbahnen Mieders", city: "innsbruck", ridersNow: 4, chillRiders: 3, parkRiders: 0, offPisteRiders: 1, conditions: "groomed", liftsOpen: 2, totalLifts: 3, snowDepth: 65, altitudeMax: 2050, altitudeMin: 960, mountainShape: 1 },
  { name: "Sölden", city: "innsbruck", ridersNow: 12, chillRiders: 4, parkRiders: 3, offPisteRiders: 5, conditions: "fresh", liftsOpen: 9, totalLifts: 12, snowDepth: 180, altitudeMax: 3340, altitudeMin: 1400, mountainShape: 2 },
  { name: "Saalbach-Hinterglemm", city: "salzburg", ridersNow: 31, chillRiders: 12, parkRiders: 8, offPisteRiders: 11, conditions: "fresh", liftsOpen: 18, totalLifts: 21, snowDepth: 105, altitudeMax: 2096, altitudeMin: 1003, mountainShape: 3 },
  { name: "Flachau", city: "salzburg", ridersNow: 26, chillRiders: 15, parkRiders: 7, offPisteRiders: 4, conditions: "groomed", liftsOpen: 11, totalLifts: 13, snowDepth: 90, altitudeMax: 1988, altitudeMin: 920, mountainShape: 4 },
  { name: "Kitzsteinhorn", city: "salzburg", ridersNow: 22, chillRiders: 7, parkRiders: 5, offPisteRiders: 10, conditions: "fresh", liftsOpen: 9, totalLifts: 10, snowDepth: 195, altitudeMax: 3029, altitudeMin: 757, mountainShape: 0 },
  { name: "Zell am See", city: "salzburg", ridersNow: 14, chillRiders: 8, parkRiders: 2, offPisteRiders: 4, conditions: "groomed", liftsOpen: 8, totalLifts: 9, snowDepth: 80, altitudeMax: 1965, altitudeMin: 757, mountainShape: 1 },
  { name: "Wagrain", city: "salzburg", ridersNow: 18, chillRiders: 10, parkRiders: 5, offPisteRiders: 3, conditions: "groomed", liftsOpen: 12, totalLifts: 14, snowDepth: 85, altitudeMax: 2000, altitudeMin: 890, mountainShape: 2 },
  { name: "Bad Gastein", city: "salzburg", ridersNow: 9, chillRiders: 4, parkRiders: 1, offPisteRiders: 4, conditions: "fresh", liftsOpen: 6, totalLifts: 8, snowDepth: 115, altitudeMax: 2686, altitudeMin: 1083, mountainShape: 3 },
  { name: "Hochkönig", city: "salzburg", ridersNow: 7, chillRiders: 4, parkRiders: 0, offPisteRiders: 3, conditions: "groomed", liftsOpen: 5, totalLifts: 7, snowDepth: 98, altitudeMax: 2941, altitudeMin: 1100, mountainShape: 4 },
];

export const LEADERBOARD_INNSBRUCK: LeaderboardEntry[] = [
  { userId: "u1", rank: 1, days: 41, xp: 5100 },
  { userId: "u3", rank: 2, days: 31, xp: 3800 },
  { userId: "u6", rank: 3, days: 19, xp: 2900 },
  { userId: "me", rank: 4, days: 23, xp: 2340 },
  { userId: "u2", rank: 5, days: 11, xp: 1200 },
  { userId: "u7", rank: 6, days: 14, xp: 1650 },
  { userId: "u4", rank: 7, days: 6, xp: 580 },
];

export const LEADERBOARD_SALZBURG: LeaderboardEntry[] = [
  { userId: "u5", rank: 1, days: 58, xp: 7200 },
  { userId: "u8", rank: 2, days: 28, xp: 4100 },
];

export const CREWS = [
  { id: "cr1", name: "IBK Pow Crew", memberIds: ["me", "u1", "u2", "u3"], city: "innsbruck" as const },
  { id: "cr2", name: "Park Rats", memberIds: ["me", "u3", "u6", "u7"], city: "innsbruck" as const },
];

export const CONVERSATIONS: Conversation[] = [
  {
    id: "conv1",
    participantIds: ["me", "u1"],
    contextType: "direct",
    messages: [
      { id: "m1", senderId: "u1", text: "Hey! Stubai tomorrow morning? Forecast says the glacier got 30cm fresh.", sentAt: "Yesterday 21:14", isRead: true },
      { id: "m2", senderId: "me", text: "For sure! What time do you want to head out?", sentAt: "Yesterday 21:20", isRead: true },
      { id: "m3", senderId: "u1", text: "8am from HBF? I'll drive.", sentAt: "Yesterday 21:22", isRead: true },
      { id: "m4", senderId: "me", text: "Perfect, I'm in!", sentAt: "Yesterday 21:25", isRead: true },
      { id: "m5", senderId: "u1", text: "Skis waxed yet?", sentAt: "1 hr ago", isRead: false },
    ],
  },
  {
    id: "conv2",
    participantIds: ["me", "u3"],
    contextType: "ride",
    contextId: "r2",
    messages: [
      { id: "m6", senderId: "u3", text: "You coming to Nordkette today? Park session.", sentAt: "Today 09:12", isRead: true },
      { id: "m7", senderId: "me", text: "Which features are open?", sentAt: "Today 09:15", isRead: true },
      { id: "m8", senderId: "u3", text: "All of them! Rails, kicker, box. Great conditions.", sentAt: "Today 09:17", isRead: false },
    ],
  },
  {
    id: "conv3",
    participantIds: ["me", "u2"],
    contextType: "direct",
    messages: [
      { id: "m9", senderId: "u2", text: "Bro Schlick was lit yesterday", sentAt: "Yesterday 17:44", isRead: true },
      { id: "m10", senderId: "me", text: "Yeah man the slopes were insane. When again?", sentAt: "Yesterday 17:50", isRead: true },
      { id: "m11", senderId: "u2", text: "Saturday?", sentAt: "Yesterday 17:51", isRead: true },
    ],
  },
];

export function getUserById(id: string): User | undefined {
  return MOCK_USERS.find((u) => u.id === id);
}

export const ME = MOCK_USERS.find((u) => u.id === "me")!;

export const LEVEL_TITLES: Record<number, string> = {
  1: "Newbie",
  2: "Rookie",
  3: "Rookie",
  4: "Local",
  5: "Regular",
  6: "Regular",
  7: "Legend",
  8: "Legend",
  9: "Pro",
  10: "Peak",
};

