-- A client may wake the Edge dispatcher after a write, but it must not be
-- able to drain notices generated by other accounts. Both public wrappers
-- remain service-role only; the scoped wrapper is the Edge entry point.
create or replace function private.take_push_outbox(
  p_actor_id uuid, p_session_id uuid, p_scoped boolean
)
returns table (endpoint text, p256dh text, auth text, kind text, actor_name text, url text)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_scoped then
    if p_actor_id is null or p_session_id is null
       or to_regclass('auth.sessions') is null then
      return;
    end if;
    if not exists (
      select 1 from auth.sessions source_session
      where source_session.id = p_session_id
        and source_session.user_id = p_actor_id
    ) then
      return;
    end if;
  end if;

  delete from private.push_outbox o
  where o.created_at < now() - interval '1 hour'
    and (not p_scoped or o.actor_id = p_actor_id);

  return query
  with taken as (
    delete from private.push_outbox o
    where o.id in (
      select q.id from private.push_outbox q
      where not p_scoped or q.actor_id = p_actor_id
      order by q.id limit 100 for update skip locked
    )
    returning o.recipient_id, o.actor_id, o.kind, o.url
  )
  select s.endpoint, s.p256dh, s.auth, t.kind,
         coalesce(a.display_name, '@' || a.handle), t.url
  from taken t
  join public.push_subscriptions s on s.user_id = t.recipient_id
  join auth.sessions recipient_session
    on recipient_session.id = s.session_id and recipient_session.user_id = s.user_id
  left join public.profiles a on a.id = t.actor_id
  where (t.actor_id is null or not private.is_blocked(t.recipient_id, t.actor_id))
    and (t.kind <> 'lift_meetup' or exists (
      select 1 from public.lift_meetups m
      where m.user_id = t.actor_id
        and m.expires_at > now()
        and private.may_share_location(m.user_id)
        and private.are_friends(t.recipient_id, m.user_id)
    ))
  limit 1000;
end;
$$;
revoke all on function private.take_push_outbox(uuid, uuid, boolean)
  from public, anon, authenticated;

create or replace function public.push_take_outbox()
returns table (endpoint text, p256dh text, auth text, kind text, actor_name text, url text)
language sql
security definer
set search_path = ''
as $$
  select * from private.take_push_outbox(null, null, false);
$$;
revoke all on function public.push_take_outbox() from public, anon, authenticated;
grant execute on function public.push_take_outbox() to service_role;

create or replace function public.push_take_session_outbox(p_actor_id uuid, p_session_id uuid)
returns table (endpoint text, p256dh text, auth text, kind text, actor_name text, url text)
language sql
security definer
set search_path = ''
as $$
  select * from private.take_push_outbox(p_actor_id, p_session_id, true);
$$;
revoke all on function public.push_take_session_outbox(uuid, uuid)
  from public, anon, authenticated;
grant execute on function public.push_take_session_outbox(uuid, uuid) to service_role;
